# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - master
  #schedule:
  #  - cron: 0 */2 * * *
  watch:
    types: [started]
          
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Set SSH Environment
      env:
        IBM_DEPLOY_KEY: ${{ secrets.IBM_DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$IBM_DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com > ~/.ssh/known_hosts
        chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
        git config --global user.email "cqc@cuiqingcai.com"
        git config --global user.name "Germey"
    - name: Sync Docs of Gerapy
      run: |
        cd /tmp
        git clone git@github.com:tnnd/php-proxy.git docs
        cd docs
        cd php-proxy/plugins
        date > git-auto.txt
        git add .
        git commit -a -m "git auto commit"
        git push origin master --force
